insert into Magazines(name) values ('Acta Inf.');
insert into Magazines(name) values ('Displays');
insert into Magazines(name) values ('IJKDB');
insert into Magazines(name) values ('Computers in Industry');
insert into Magazines(name) values ('International Journal of Internet and Enterprise Management');
insert into Magazines(name) values ('Future Generation Comp. Syst.');
insert into Magazines(name) values ('Telematics and Informatics');
insert into Magazines(name) values ('IJEA');
insert into Magazines(name) values ('Game Studies');
insert into Magazines(name) values ('IJTM');
insert into Magazines(name) values ('IEEE Trans. Knowl. Data Eng.');
insert into Magazines(name) values ('Higher-Order and Symbolic Computation');
insert into Magazines(name) values ('Lisp and Symbolic Computation');
insert into Magazines(name) values ('Knowl.-Based Syst.');
insert into Magazines(name) values ('IJEBR');
insert into Magazines(name) values ('I. J. Artificial Intelligence in Education');
insert into Magazines(name) values ('Markup Languages');
insert into Magazines(name) values ('Journal of Intelligent and Fuzzy Systems');
insert into Magazines(name) values ('Foundations and Trends in Programming Languages');
insert into Magazines(name) values ('Computational Statistics n Data Analysis');
insert into Magazines(name) values ('Web Intelligence and Agent Systems');
insert into Magazines(name) values ('Web Intelligence');
insert into Magazines(name) values ('J. Formalized Reasoning');
insert into Magazines(name) values ('ERCIM News');
insert into Magazines(name) values ('J. Data Semantics');
insert into Magazines(name) values ('IJIEI');
insert into Magazines(name) values ('IJWMIP');
insert into Magazines(name) values ('Combinatorica');
insert into Magazines(name) values ('Int. J. Cooperative Inf. Syst.');
insert into Magazines(name) values ('Int. Arab J. Inf. Technol.');
insert into Magazines(name) values ('Applied Categorical Structures');
insert into Magazines(name) values ('IJICST');
insert into Magazines(name) values ('EAI Endorsed Trans. Ambient Systems');
insert into Magazines(name) values ('ICST Trans. Ambient Systems');
insert into Magazines(name) values ('Computer and Information Science');
insert into Magazines(name) values ('Smart CR');
insert into Magazines(name) values ('JUSPN');
insert into Magazines(name) values ('IJAMC');
insert into Magazines(name) values ('EJIS');
insert into Magazines(name) values ('Automatica');
insert into Magazines(name) values ('J. Information Security');
insert into Magazines(name) values ('Bulletin of Symbolic Logic');
insert into Magazines(name) values ('JOCCH');
insert into Magazines(name) values ('IJANTTI');
insert into Magazines(name) values ('IJWP');
insert into Magazines(name) values ('IEEE T. Human-Machine Systems');
insert into Magazines(name) values ('IEEE Transactions on Information Forensics and Security');
insert into Magazines(name) values ('IJMSTR');
insert into Magazines(name) values ('Linguamática');
insert into Magazines(name) values ('Foundations and Trends in Signal Processing');
insert into Magazines(name) values ('Journal of Zhejiang University - Science C');
insert into Magazines(name) values ('Frontiers of IT n EE');
insert into Magazines(name) values ('Computer Vision, Graphics, and Image Processing');
insert into Magazines(name) values ('Graphical Models');
insert into Magazines(name) values ('CVGIP: Graphical Model and Image Processing');
insert into Magazines(name) values ('Graphical Models and Image Processing');
insert into Magazines(name) values ('Computer Graphics and Image Processing');
insert into Magazines(name) values ('IJHISI');
insert into Magazines(name) values ('TACO');
insert into Magazines(name) values ('IJTHI');
insert into Magazines(name) values ('Groups Complexity Cryptology');
insert into Magazines(name) values ('SIGART Bulletin');
insert into Magazines(name) values ('Intelligence');
insert into Magazines(name) values ('Robotersysteme');
insert into Magazines(name) values ('Int. Journal in Computer Simulation');
insert into Magazines(name) values ('Algorithmica');
insert into Magazines(name) values ('International Journal of Software Engineering and Knowledge Engineering');
insert into Magazines(name) values ('Journal of Circuits, Systems, and Computers');
insert into Magazines(name) values ('Formal Methods in System Design');
insert into Magazines(name) values ('J. Cryptology');
insert into Magazines(name) values ('Journal of Computer Security');
insert into Magazines(name) values ('J. Comput. Physics');
insert into Magazines(name) values ('Foundations and Trends in Databases');
insert into Magazines(name) values ('SIAM J. Scientific Computing');
insert into Magazines(name) values ('Math. Log. Q.');
insert into Magazines(name) values ('IEEE T. Haptics');
insert into Magazines(name) values ('Computers');
insert into Magazines(name) values ('IJHCITP');
insert into Magazines(name) values ('J. Sensor Technology');
insert into Magazines(name) values ('Personal and Ubiquitous Computing');
insert into Magazines(name) values ('SIGSPATIAL Special');
insert into Magazines(name) values ('J. Comput. Sci. Technol.');
insert into Magazines(name) values ('Intelligent Decision Technologies');
insert into Magazines(name) values ('Expert Systems');
insert into Magazines(name) values ('Synthese');
insert into Magazines(name) values ('IJEP');
insert into Magazines(name) values ('IEEE Security n Privacy');
insert into Magazines(name) values ('IJSIR');
insert into Magazines(name) values ('World Digital Libraries');
insert into Magazines(name) values ('JACIII');
insert into Magazines(name) values ('Axioms');
insert into Magazines(name) values ('FO n DM');
insert into Magazines(name) values ('Int. J. Pervasive Computing and Communications');
insert into Magazines(name) values ('Int. J. Game Theory');
insert into Magazines(name) values ('Peer-to-Peer Networking and Applications');
insert into Magazines(name) values ('IEEE Trans. Education');
insert into Magazines(name) values ('Meth. of Logic in CS');
insert into Magazines(name) values ('IEEE Transactions on Neural Networks');
insert into Magazines(name) values ('IEEE Trans. Neural Netw. Learning Syst.');
insert into Magazines(name) values ('IJPOP');
insert into Magazines(name) values ('Computer Science Education');
insert into Magazines(name) values ('Statistical Analysis and Data Mining');
insert into Magazines(name) values ('Neural Parallel n Scientific Comp.');
insert into Magazines(name) values ('J. Electron. Commerce Res.');
insert into Magazines(name) values ('IJCOPI');
insert into Magazines(name) values ('Math. Program. Comput.');
insert into Magazines(name) values ('OR Insight');
insert into Magazines(name) values ('IEEE Transactions on Information Technology in Biomedicine');
insert into Magazines(name) values ('IEEE J. Biomedical and Health Informatics');
insert into Magazines(name) values ('Ingénierie des Systèmes d'Information');
insert into Magazines(name) values ('JTHTL');
insert into Magazines(name) values ('Inf. Retr. Journal');
insert into Magazines(name) values ('Inf. Retr.');
insert into Magazines(name) values ('IEEE Trans. Biomed. Circuits and Systems');
insert into Magazines(name) values ('Appl. Algebra Eng. Commun. Comput.');
insert into Magazines(name) values ('Wireless Communications and Mobile Computing');
insert into Magazines(name) values ('J. Low Power Electronics');
insert into Magazines(name) values ('JOOP');
insert into Magazines(name) values ('The Review of Socionetwork Strategies');
insert into Magazines(name) values ('IEICE Electronic Express');
insert into Magazines(name) values ('iJEP');
insert into Magazines(name) values ('Rel. Eng. n Sys. Safety');
insert into Magazines(name) values ('Cluster Computing');
insert into Magazines(name) values ('J. Database Manag.');
insert into Magazines(name) values ('Informatics in Education');
insert into Magazines(name) values ('JASIS');
insert into Magazines(name) values ('JASIST');
insert into Magazines(name) values ('Comput. Sci. Inf. Syst.');
insert into Magazines(name) values ('IJDAR');
insert into Magazines(name) values ('Enterprise Modelling and Information Systems Architectures');
insert into Magazines(name) values ('Journal of Graph Theory');
insert into Magazines(name) values ('IJERTCS');
insert into Magazines(name) values ('IJDSN');
insert into Magazines(name) values ('IJSNM');
insert into Magazines(name) values ('IJITM');
insert into Magazines(name) values ('Cybernetics and Systems');
insert into Magazines(name) values ('Kognitionswissenschaft');
insert into Magazines(name) values ('IET Software');
insert into Magazines(name) values ('IEE Proceedings - Software');
insert into Magazines(name) values ('Ann. Pure Appl. Logic');
insert into Magazines(name) values ('ACM Crossroads');
insert into Magazines(name) values ('Multimedia Syst.');
insert into Magazines(name) values ('Earth Science Informatics');
insert into Magazines(name) values ('D-Lib Magazine');
